Corrigiendo despliegues

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,11 @@ jobs:
             cd /var/www/goWash/\$PROCESS_NAME || exit 1
             git pull origin main
             npm install
+            npm run test
+            if [ $? -ne 0 ]; then
+              echo "Tests failed. Deployment aborted."
+              exit 1
+            fi
             npm run build
 
              PROCESS_NAME=\$PROCESS_NAME
